INSERT INTO UNICORN (ID, NAME, AGE, COLOR, HORN, FLY_ABLE, PRICE) VALUES (100000L, 'Twilight', 4, 1, true, false, 124100.00);
INSERT INTO UNICORN (ID, NAME, AGE, COLOR, HORN, FLY_ABLE, PRICE) VALUES (100001L, 'Stardust', 1, 0, false, true, 129199.99);
INSERT INTO UNICORN (ID, NAME, AGE, COLOR, HORN, FLY_ABLE, PRICE) VALUES (100002L, 'Buttercup', 1, 0, false, false, 71199.99);
INSERT INTO UNICORN (ID, NAME, AGE, COLOR, HORN, FLY_ABLE, PRICE) VALUES (100003L, 'Sparkles', 9, 3, true, true, 120199.99);

INSERT INTO CUSTOMER (USERNAME, PASSWORD, EMAIL, FIRST_NAME, LAST_NAME, ADDRESS, ZIP_CODE, CITY) VALUES('woow_man', '1234a5', 'asd@hotmail.com', 'Johan', 'Mattsson', 'Backsippsgatan 17', '72224', 'Vasteras');
INSERT INTO CUSTOMER (USERNAME, PASSWORD, EMAIL, FIRST_NAME, LAST_NAME, ADDRESS, ZIP_CODE, CITY) VALUES('cm91', '87qew965', 'qwe@gmail.com', 'Carl', 'Mickelson', 'Repslagargatan 3B', '97321', 'Luleo');
INSERT INTO CUSTOMER (USERNAME, PASSWORD, EMAIL, FIRST_NAME, LAST_NAME, ADDRESS, ZIP_CODE, CITY) VALUES('alvisen', '99fge68', 'cool@outlook.com', 'Alva', 'Storm', 'Nordostpassagen 51', '41311', 'Goteborg');
INSERT INTO CUSTOMER (USERNAME, PASSWORD, EMAIL, FIRST_NAME, LAST_NAME, ADDRESS, ZIP_CODE, CITY) VALUES('carro_91', '123', 'carro_91@hotmail.com', 'Caroline', 'Brander Lof', 'Daltorpsgatan 52', '41273', 'Goteborg');


