CREATE TABLE UNICORN(
  ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  NAME VARCHAR(64) NOT NULL,
  AGE INT NOT NULL,
  RANK VARCHAR(20) NOT NULL UNIQUE,
  HORN BIT NOT NULL,
  FLY_ABLE BIT NOT NULL,
  PRICE DECIMAL NOT NULL
);
CREATE TABLE UNICORN(
  ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  NAME VARCHAR(64) NOT NULL,
  AGE INT NOT NULL,
  COLORS VARCHAR(20) NOT NULL,
  HORN BIT NOT NULL,
  FLY_ABLE BIT NOT NULL,
  PRICE DECIMAL NOT NULL
);

CREATE TABLE CUSTOMER(
  ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  USERNAME VARCHAR(64),
  PASSWORD VARCHAR(64),
  EMAIL VARCHAR(64),
  FIRST_NAME VARCHAR(64),
  LAST_NAME VARCHAR(64),
  ADDRESS VARCHAR(200),
  ZIP_CODE VARCHAR(10),
  CITY VARCHAR(64)
);

CREATE TABLE ORDERS(
  ORDER_NUMBER BIGINT AUTO_INCREMENT PRIMARY KEY,
  UNICORN_ID BIGINT NOT NULL,
  CUSTOMER_ID BIGINT NOT NULL
);

ALTER TABLE ORDERS ADD FOREIGN KEY (UNICORN_ID) REFERENCES UNICORN(ID);
ALTER TABLE ORDERS ADD FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(ID);
